### ISSUE TITLE
`ceiling.integer64()` returns floor value

### ISSUE THREAD

**Issue by Rosie23** [r-lib/bit64#35]
`ceiling.integer64(as.integer64(x))` returns same output as `as.integer64(base::floor(x))` rather than `as.integer64(base::ceiling(x))` as expected

```
ceiling.integer64(as.integer64(1.1)) # 1
as.integer64(base::floor(x)) # 1
as.integer64(base:: ceiling(x)) # 2
```

**Comment by MichaelChirico** [comment]
The truncation is by `as.integer64()`:

```r
as.integer64(1.1)
# integer64
# [1] 1
```

`integer64` is, well, an integer class, so we don't expect `ceiling()`/`floor()` to really _do_ anything since those functions are concerned with fractions. The only reason `ceiling.integer64()` exists is so that the integer64 _class_ is not lost when an integer64 input is met.

The methods in fact trivially just return their arguments:

https://github.com/r-lib/bit64/blob/aac1b607a4c58414311f287c0c3f3346bc432461/R/integer64.R#L2575

As a further point, you should not compare `as.integer64(base::ceiling(1.1))` but `ceiling(as.integer(1.1))` which returns the same as for integer64.
