### ISSUE TITLE
colSums/rowSums do not work when as.integer64(NA) is present in data.table

### ISSUE THREAD

**Issue by vlulla** [r-lib/bit64#38]
It appears that `colSums`/`rowSums` do not handle `as.integer64(NA)` appropriately. Below snippet demonstrates the issue:

```R
i64v = as.integer64(c(12345678901234, 70, 20, NA))
apple = data.table(id = c("a", "b", "b"), time = c(1L, 1L, 2L), y = i64v[1:3])
colSums(dcast(apple, id ~ time, value.var = "y")[,-1,with=FALSE])
#             1             2
# 6.099576e-311 9.881313e-323
colSums(dcast(apple, id ~ time, value.var = "y")[,-1,with=FALSE], na.rm=TRUE)
#             1             2
# 6.099576e-311 9.881313e-323
rowSums(dcast(apple, id ~ time, value.var = "y")[,-1,with=FALSE], na.rm=TRUE)
# [1] 6.099576e-311 4.446591e-322
rowSums(dcast(apple,id~time,value.var="y")[2,-1,with=FALSE])
# [1] 4.446591e-322
dcast(apple,id~time,value.var="y")[2,sum(`1`,`2`)] ## surprised that this works!
# integer64
# [1] 90
```

I posted this question on data.table issues page and was instructed to raise this issue here. Please let me know if I can do anything to help. And, thanks in advance!

**Comment by MichaelChirico** [comment]
The last example works because there is a `sum.integer64` method; the `colSums`/`rowSums` do not because there are no `integer64` methods (especially because they are not S3 generics in base R). So R only sees the input as doubles (and the double representation of `NA_integer64_` is not the same as that of `NA_real_`).
